#ifndef COLLECT_VIEW_OPENMOTE_CC2538_H
#define COLLECT_VIEW_OPENMOTE_CC2538_H

#include "collect-view.h"

enum {
  ACCELERATION_SENSOR,
  BUTTON_USER_SENSOR,
  VDD3_SENSOR,
  LIGHT_SENSOR,
  TEMP_SENSOR,
  HUMIDITY_SENSOR,
  DUMMY_SENSOR,
  ACCELEROMETER_X_SENSOR,
  ACCELEROMETER_Y_SENSOR,
  ACCELEROMETER_Z_SENSOR,
};

#endif /* COLLECT_VIEW_OPENMOTE_CC2538_H */
